In [1]:
%load_ext autoreload
%autoreload 2

import sys


sys.path.append('/Users/pnecchi/Documents/Projects/fantatech/')

from fantatech.startup import *

<ipython-input-1-57a1ffc2ed25>:9: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  from fantatech.startup import *

In [2]:
p = player

# Single player

In [8]:
show_players_stats(p.freuler)

,Ruolo,Mantra,Squadra,Quotazione,Fv* (2017),Fv* (2018),Fv* (2019),quantileOrder
Nome,,,,,,,,
Freuler,C,C,Atalanta,8.0,6.52,6.3,6.18,0.53

# Multiplayer (last year)

In [337]:
show_players_stats([
    player.caicedo, 
    player.dybala,
    player.gomez, 
    player.joao_pedro, 
    player.osimhen, 
], years=2019)